### ISSUE TITLE
How to handle follow up questions for created data

### ISSUE THREAD

**Issue by Reshadaliyevr** [gabrielchua/DAVE#1]
I have been trying to make it possible for user to ask follow up questions about the response that assistant generated but I am not able to do that. Can you please help me to add this function? I think it is must have function for this application.

**Comment by gabrielchua** [comment]
Hi @Reshadaliyevr  - you can check out the `chat_app.py` script within the repo.

This has the conversational flow, similar to streamlit's chatbots.

It won't run out of the box, but I think you can make the changes by adding the OAI API key etc. 

Let me know if you run into any issues.
