### ISSUE TITLE
Images not shown

### ISSUE THREAD

**Issue by lenisha** [gabrielchua/DAVE#2]
Tried app.py to run and display the plots
It generated code correctly but image never shown and function in EventHandler.on_image_file_done(self, image_file: ImageFile) is never called.

Code interpreter generates correct code though:
```
import matplotlib.pyplot as plt

# Drop rows with missing scores
data = data.dropna(subset=['Score'])

# Plot the distribution of scores
plt.figure(figsize=(10, 6))
plt.hist(data['Score'], bins=20, edgecolor='black')
plt.title('Distribution of Scores')
plt.xlabel('Score')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()
```

What is missing to display images?
@gabrielchua

**Comment by gabrielchua** [comment]
@lenisha - yea I had this same issue too. 

I found an earlier post in the openai forum where they tried to resolve this by asking the model to always save the image as `.svg`.

I also tried an implementation without using the openai sdk's `EventHandler`. In [`chat_app.py`](https://github.com/gabrielchua/DAVE/blob/main/chat_app.py), you can refer to line 194 to 215 - hope that helps
